force-app/main/default/objects/Habilidad__c/Habilidad__c.object-meta.xml
<CustomObject>
    <label>Habilidad</label>
    <nameField>
        <label>Habilidad Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Habilidades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Habilidad__c/fields/ExtId__c.field-meta.xml
<CustomField>
    <fullName>ExtId__c</fullName>
    <label>ExtId</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Movimiento__c/Movimiento__c.object-meta.xml
<CustomObject>
    <label>Movimiento</label>
    <nameField>
        <label>Movimiento Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Movimientos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Pokemon__c/Pokemon__c.object-meta.xml
<CustomObject>
    <label>Pokemon</label>
    <nameField>
        <label>Pokemon Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pokemons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Pokemon__c/fields/Ataque__c.field-meta.xml
<CustomField>
    <fullName>Ataque__c</fullName>
    <label>Ataque</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Pokemon__c/fields/Defensa__c.field-meta.xml
<CustomField>
    <fullName>Defensa__c</fullName>
    <label>Defensa</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Pokemon__c/fields/Habilidad__c.field-meta.xml
<CustomField>
    <fullName>Habilidad__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Habilidad</label>
    <referenceTo>Habilidad__c</referenceTo>
    <relationshipLabel>Pokemons</relationshipLabel>
    <relationshipName>Pokemons</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Pokemon__c/fields/Imagen__c.field-meta.xml
<CustomField>
    <fullName>Imagen__c</fullName>
    <label>Imagen</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Pokemon__c/fields/Slot1__c.field-meta.xml
<CustomField>
    <fullName>Slot1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Slot1</label>
    <referenceTo>Movimiento__c</referenceTo>
    <relationshipLabel>Pokemons</relationshipLabel>
    <relationshipName>Pokemons</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Pokemon__c/fields/Slot2__c.field-meta.xml
<CustomField>
    <fullName>Slot2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Slot2</label>
    <referenceTo>Movimiento__c</referenceTo>
    <relationshipLabel>Pokemons (Slot2)</relationshipLabel>
    <relationshipName>Pokemons1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Pokemon__c/fields/Slot3__c.field-meta.xml
<CustomField>
    <fullName>Slot3__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Slot3</label>
    <referenceTo>Movimiento__c</referenceTo>
    <relationshipLabel>Pokemons (Slot3)</relationshipLabel>
    <relationshipName>Pokemons2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Pokemon__c/fields/Slot4__c.field-meta.xml
<CustomField>
    <fullName>Slot4__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Slot4</label>
    <referenceTo>Movimiento__c</referenceTo>
    <relationshipLabel>Pokemons (Slot4)</relationshipLabel>
    <relationshipName>Pokemons3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Pokemon__c/fields/Tipos__c.field-meta.xml
<CustomField>
    <fullName>Tipos__c</fullName>
    <label>Tipos</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Bug</fullName>
            </value>
            <value>
                <fullName>Dark</fullName>
            </value>
            <value>
                <fullName>Dragon</fullName>
            </value>
            <value>
                <fullName>Electric</fullName>
            </value>
            <value>
                <fullName>Fairy</fullName>
            </value>
            <value>
                <fullName>Fighting</fullName>
            </value>
            <value>
                <fullName>Fire</fullName>
            </value>
            <value>
                <fullName>Flying</fullName>
            </value>
            <value>
                <fullName>Ghost</fullName>
            </value>
            <value>
                <fullName>Grass</fullName>
            </value>
            <value>
                <fullName>Ground</fullName>
            </value>
            <value>
                <fullName>Ice</fullName>
            </value>
            <value>
                <fullName>Normal</fullName>
            </value>
            <value>
                <fullName>Poison</fullName>
            </value>
            <value>
                <fullName>Psychic</fullName>
            </value>
            <value>
                <fullName>Rock</fullName>
            </value>
            <value>
                <fullName>Steel</fullName>
            </value>
            <value>
                <fullName>Water</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Pokemon__c/fields/TiposFiltrados__c.field-meta.xml
<CustomField>
    <fullName>TiposFiltrados__c</fullName>
    <label>TiposFiltrados</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Pokemon__c/fields/Velocidad__c.field-meta.xml
<CustomField>
    <fullName>Velocidad__c</fullName>
    <label>Velocidad</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Pokemon__c/fields/Vida__c.field-meta.xml
<CustomField>
    <fullName>Vida__c</fullName>
    <label>Vida</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/GetPokemonsBatch.cls
global class GetPokemonsBatch implements Database.Batchable<Integer>, Database.AllowsCallouts, Database.Stateful {
    
    //Llamada
    /*List<Integer> numero = new List<Integer>();
    for(Integer i = 1; i<=898; i++){
    	numero.add(i);
    }
    
    
    Database.executeBatch(new GetPokemonsBatch(numero),1);*/
    
    List<Integer> cantidadPokemons = new List<Integer>();
    
    public GetPokemonsBatch(List<Integer> cantidadPokemons){
        this.cantidadPokemons = cantidadPokemons;
    }
    
    global Iterable<Integer> start(Database.BatchableContext bc) {       
        return cantidadPokemons;
    }
    
    global void execute(Database.BatchableContext bc, List<Integer> cantidadPokemons){
        //List<Pokemon__c> pokemones = new List<Pokemon__c>();
        try {
            
            Http http = new Http();
            
            HttpRequest request = new HttpRequest();                
            request.setEndpoint('https://pokeapi.co/api/v2/pokemon/'+cantidadPokemons[0]);
            request.setMethod('GET');
            request.setHeader('Accept', 'application/json');
            
            HttpResponse response = http.send(request);
            
            Map<String, Object> results = (Map<String, Object>)JSON.deserializeUntyped(response.getBody());
            
            Pokemon__c pokemon = new Pokemon__c();
            String name = (string) results.get('name');
            pokemon.Name = name.Capitalize();
            pokemon.Altura__c = (Integer) results.get('height')+ ' mts.';
            pokemon.Peso__c = (Integer) results.get('weight')+ ' kg.';
            pokemon.ExtId__c = (Integer) results.get('id');
            
            
            
            
            Map<String, Object> sprites = (Map<String,Object>) results.get('sprites');
            Map<String, Object> sprite = (Map<String,Object>) sprites.get('other');
            Map<String, Object> spriteHome = (Map<String,Object>) sprite.get('home');
            
            Map<String, Object> spriteGif = (Map<String,Object>) sprites.get('versions');
            Map<String, Object> spriteGeneracion5 = (Map<String,Object>) spriteGif.get('generation-v');
            Map<String, Object> spriteBlackWhite = (Map<String,Object>) spriteGeneracion5.get('black-white');
            Map<String, Object> spriteAnimated = (Map<String,Object>) spriteBlackWhite.get('animated');
            
            pokemon.Imagen__c = (String) spriteAnimated.get('front_default') == null
                ? (String) spriteHome.get('front_default')
                : (String) spriteAnimated.get('front_default');
            
            
            
            
            List<Object>stats = (List<Object>) results.get('stats');          
            for(Integer i = 0; i < stats.size(); i++){
                Map<String, Object> statt = (Map<String,Object>) stats[i];
                Map<String, Object> estadistica = (Map<String,Object>) statt.get('stat');
                String statName = (String) estadistica.get('name');
                if(statName.equals('hp')){        
                    pokemon.Vida__c = (Integer) statt.get('base_stat');
                }else if(statName.equals('attack')){
                    pokemon.Ataque__c = (Integer) statt.get('base_stat');
                }else if(statName.equals('defense')){
                    pokemon.Defensa__c = (Integer) statt.get('base_stat');
                }else if(statName.equals('speed')){
                    pokemon.Velocidad__c = (Integer) statt.get('base_stat');
                }               
            }
            
            
            
            List<Object> habilidades = (List<Object>) results.get('abilities');
            Map<String,Object> habilidadAleatoria = (Map<String,Object>) habilidades.get(Integer.valueOf(Math.random()*habilidades.size()));
            Map<String,Object> habilidad = (Map<String,Object>) habilidadAleatoria.get('ability');
            String habilidadNombre = (String) habilidad.get('name');
            
            Habilidad__c encontrarHabilidad = [SELECT Id 
                                               FROM Habilidad__c
                                               WHERE Name = :habilidadNombre.capitalize()
                                               LIMIT 1];
            
            pokemon.Habilidad__c = encontrarHabilidad.Id;
            
            
            
            
            List<Object> tipos = (List<Object>) results.get('types');                
            for(integer i = 0; i < tipos.size(); i++){
                
                Map<String, Object> tipo = (Map<String,Object>) tipos[i];
                Map<String, Object> tipoNombre = (Map<String,Object>) tipo.get('type');
                String nombre = (String) tipoNombre.get('name');
                pokemon.Tipos__c = pokemon.Tipos__c == null
                    ? nombre.capitalize()
                    : pokemon.Tipos__c + ';' + nombre.capitalize();
                pokemon.TiposFiltrados__c = pokemon.TiposFiltrados__c == null
                    ? nombre.capitalize()
                    : pokemon.TiposFiltrados__c + '-' + nombre.capitalize(); 
            }
            
            
            
            
            List<Object> movimientos = (List<Object>) results.get('moves');
            Set<Integer> numeros = new Set<Integer>();
            
            while(numeros.size()<movimientos.size()){
                Integer numeroAleatorio = Integer.valueof((Math.random() * movimientos.size()));
                numeros.add(numeroAleatorio);
            }    
            
            List<Integer> hashSetNumeros = new List<Integer>(numeros); 
            
            for(Integer j = 0; j < movimientos.size(); j++){
                
                Map<String,Object> movimientoAleatorio = (Map<String,Object>) movimientos.get(hashSetNumeros[j]);
                Map<String, Object> movimiento = (Map<String,Object>) movimientoAleatorio.get('move');
                String movimientoNombre = (String) movimiento.get('name');
                
                switch on j{
                    when 0{
                        Movimiento__c encontrarMovimiento = [SELECT Id 
                                                             FROM  Movimiento__c
                                                             WHERE Name = :movimientoNombre.capitalize()
                                                             LIMIT 1];
                        pokemon.Slot1__c = encontrarMovimiento.Id;
                    } 
                    when 1{
                        Movimiento__c encontrarMovimiento = [SELECT Id 
                                                             FROM  Movimiento__c
                                                             WHERE Name = :movimientoNombre.capitalize()
                                                             LIMIT 1];
                        pokemon.Slot2__c = encontrarMovimiento.Id;
                    }
                    when 2{
                        Movimiento__c encontrarMovimiento = [SELECT Id 
                                                             FROM  Movimiento__c
                                                             WHERE Name = :movimientoNombre.capitalize()
                                                             LIMIT 1];
                        pokemon.Slot3__c = encontrarMovimiento.Id;
                    }
                    when 3{
                        Movimiento__c encontrarMovimiento = [SELECT Id 
                                                             FROM  Movimiento__c
                                                             WHERE Name = :movimientoNombre.capitalize()
                                                             LIMIT 1];
                        pokemon.Slot4__c = encontrarMovimiento.Id;
                        break;
                    }
                }
            }    
            
            //pokemones.add(pokemon);
            //System.debug(pokemones);
            insert pokemon;
        } catch (Exception e) {
            System.debug('ERROR :' + e.getMessage());
        }
    }
    global void finish(Database.BatchableContext bc){
        System.debug('Batch GetPokemons finalizado satisfactoriamente');
    }
}