force-app/main/default/objects/Movimiento__c/Movimiento__c.object-meta.xml
<CustomObject>
    <label>Movimiento</label>
    <nameField>
        <label>Movimiento Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Movimientos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Movimiento__c/fields/Chance_de_Efecto__c.field-meta.xml
<CustomField>
    <fullName>Chance_de_Efecto__c</fullName>
    <label>Chance de Efecto</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Movimiento__c/fields/Efecto__c.field-meta.xml
<CustomField>
    <fullName>Efecto__c</fullName>
    <label>Efecto</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Movimiento__c/fields/Objetivo__c.field-meta.xml
<CustomField>
    <fullName>Objetivo__c</fullName>
    <label>Objetivo</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Movimiento__c/fields/Poder__c.field-meta.xml
<CustomField>
    <fullName>Poder__c</fullName>
    <label>Poder</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Movimiento__c/fields/Pp__c.field-meta.xml
<CustomField>
    <fullName>Pp__c</fullName>
    <label>Pp</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Movimiento__c/fields/Prioridad__c.field-meta.xml
<CustomField>
    <fullName>Prioridad__c</fullName>
    <label>Prioridad</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Movimiento__c/fields/Punteria__c.field-meta.xml
<CustomField>
    <fullName>Punteria__c</fullName>
    <label>Punteria</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Movimiento__c/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <label>Tipo</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Normal</fullName>
            </value>
            <value>
                <fullName>Fighting</fullName>
            </value>
            <value>
                <fullName>Flying</fullName>
            </value>
            <value>
                <fullName>Poison</fullName>
            </value>
            <value>
                <fullName>Ground</fullName>
            </value>
            <value>
                <fullName>Rock</fullName>
            </value>
            <value>
                <fullName>Bug</fullName>
            </value>
            <value>
                <fullName>Ghost</fullName>
            </value>
            <value>
                <fullName>Steel</fullName>
            </value>
            <value>
                <fullName>Fire</fullName>
            </value>
            <value>
                <fullName>Water</fullName>
            </value>
            <value>
                <fullName>Grass</fullName>
            </value>
            <value>
                <fullName>Electric</fullName>
            </value>
            <value>
                <fullName>Psychic</fullName>
            </value>
            <value>
                <fullName>Ice</fullName>
            </value>
            <value>
                <fullName>Dragon</fullName>
            </value>
            <value>
                <fullName>Dark</fullName>
            </value>
            <value>
                <fullName>Fairy</fullName>
            </value>
            <value>
                <fullName>Unknown</fullName>
            </value>
            <value>
                <fullName>Shadow</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/GetMovesBatch.cls
global class GetMovesBatch implements Database.Batchable<Integer>, Database.AllowsCallouts, Database.Stateful {
    
    //Llamada
    /*List<Integer> numero = new List<Integer>();
    for(Integer i = 1; i<=826; i++){
        numero.add(i);
    }
    
    
    Database.executeBatch(new GetMovesBatch(numero),1);*/
    
    List<Integer> cantidadMovimientos = new List<Integer>();
    public GetMovesBatch(List<Integer> cantidadMovimientos){
        this.cantidadMovimientos = cantidadMovimientos;
    }
    
    global Iterable<Integer> start(Database.BatchableContext bc) {       
        return cantidadMovimientos;
    }
    
    global void execute(Database.BatchableContext bc, List<Integer> cantidadMovimientos){
        //List<Movimiento__c> movimientos = new List<Movimiento__c>();
        try {
            
            Http http = new Http();
            
            HttpRequest request = new HttpRequest();                
            request.setEndpoint('https://pokeapi.co/api/v2/move/'+cantidadMovimientos[0]);
            request.setMethod('GET');
            request.setHeader('Accept', 'application/json');
            
            HttpResponse response = http.send(request);
            
            Map<String, Object> results = (Map<String, Object>)JSON.deserializeUntyped(response.getBody());
            
            Movimiento__c movimiento = new Movimiento__c();
            String name = (string) results.get('name');
            movimiento.Name = name.Capitalize();
            movimiento.ExtId__c = (Integer) results.get('id');
            movimiento.Punteria__c = (Integer) results.get('accuracy') == null
                ? 0
                : (Integer) results.get('accuracy');
            movimiento.Chance_de_Efecto__c = (Integer) results.get('effect_chance') == null 
                ? 0 
                : (Integer) results.get('effect_chance');
            
            movimiento.Prioridad__c = (Integer) results.get('priority') == null
                ? 0
                : (Integer) results.get('priority');
            
            movimiento.Poder__c = (Integer) results.get('power') == null
                ? 0
                : (Integer) results.get('power');
            movimiento.Pp__c = (Integer) results.get('pp') == null
                ? 0
                : (Integer) results.get('pp');
            
            
            
            
            Map<String, Object> target = (Map<String, Object>) results.get('target');
            movimiento.Objetivo__c = (String) target.get('name');
            
            

            
            
            List<Object> effectEntries =(List<Object>) results.get('effect_entries');
            if (effectEntries.size() > 0 ){
                for(Integer i = 0; i < effectEntries.size(); i++){
                    Map<String,Object> searchEnglish = (Map<String,Object>) effectEntries.get(i);
                    Map<String,Object> language = (Map<String,Object>) searchEnglish.get('language');
                    String languageName = (String) language.get('name');
                    if (languageName.equals('en')){
                        movimiento.Efecto__c = (String) searchEnglish.get('short_effect');
                    } else {
                        movimiento.Efecto__c = '';
                    }
                }
            }else{
                movimiento.Efecto__c = '';
            } 
            
            
            
            
            
            Map<String, Object> tipo = (Map<String, Object>) results.get('type'); 
            movimiento.Tipo__c = (String) tipo.get('name');
            
            //movimientos.add(movimiento);
            //system.debug(movimientos);
            insert movimiento;
        } catch (Exception e) {
            System.debug('ERROR :' + e.getMessage());
        }
    }
    
    global void finish(Database.BatchableContext bc){
        System.debug('Batch GetMoves finalizado satisfactoriamente');
    }
}