force-app/main/default/objects/Pokemon__c/Pokemon__c.object-meta.xml
<CustomObject>
    <label>Pokemon</label>
    <nameField>
        <label>Pokemon Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pokemons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Pokemon__c/fields/Generacion__c.field-meta.xml
<CustomField>
    <fullName>Generacion__c</fullName>
    <formula>IF(ExtId__c  &gt;=1  &amp;&amp;  ExtId__c  &lt;=151, 1, (
 IF(ExtId__c  &gt;151  &amp;&amp;  ExtId__c  &lt;=251, 2, (
 IF(ExtId__c  &gt;251  &amp;&amp;  ExtId__c  &lt;=386, 3, (
 IF(ExtId__c  &gt;386  &amp;&amp;  ExtId__c  &lt;=493, 4, (
 IF(ExtId__c  &gt;493  &amp;&amp;  ExtId__c  &lt;=649, 5, (
 IF(ExtId__c  &gt;649  &amp;&amp;  ExtId__c  &lt;=721, 6, (
 IF(ExtId__c  &gt;721  &amp;&amp;  ExtId__c  &lt;=809, 7, (
 IF(ExtId__c  &gt;809  &amp;&amp;  ExtId__c  &lt;=898, 8, 0) )) )) )) )) )) )) ))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Generacion</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Pokemon__c/fields/Imagen__c.field-meta.xml
<CustomField>
    <fullName>Imagen__c</fullName>
    <label>Imagen</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Pokemon__c/fields/Tipos__c.field-meta.xml
<CustomField>
    <fullName>Tipos__c</fullName>
    <label>Tipos</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Bug</fullName>
            </value>
            <value>
                <fullName>Dark</fullName>
            </value>
            <value>
                <fullName>Dragon</fullName>
            </value>
            <value>
                <fullName>Electric</fullName>
            </value>
            <value>
                <fullName>Fairy</fullName>
            </value>
            <value>
                <fullName>Fighting</fullName>
            </value>
            <value>
                <fullName>Fire</fullName>
            </value>
            <value>
                <fullName>Flying</fullName>
            </value>
            <value>
                <fullName>Ghost</fullName>
            </value>
            <value>
                <fullName>Grass</fullName>
            </value>
            <value>
                <fullName>Ground</fullName>
            </value>
            <value>
                <fullName>Ice</fullName>
            </value>
            <value>
                <fullName>Normal</fullName>
            </value>
            <value>
                <fullName>Poison</fullName>
            </value>
            <value>
                <fullName>Psychic</fullName>
            </value>
            <value>
                <fullName>Rock</fullName>
            </value>
            <value>
                <fullName>Steel</fullName>
            </value>
            <value>
                <fullName>Water</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Pokemon__c/fields/TiposFiltrados__c.field-meta.xml
<CustomField>
    <fullName>TiposFiltrados__c</fullName>
    <label>TiposFiltrados</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/PokemonController.cls
public with sharing class PokemonController {

    @AuraEnabled(Cacheable=true)
    public static Pokemon__c[] searchPokemons(String tipo, Integer generacion
    , String searchTerm, String orden) {

        searchTerm = searchTerm.trim();

        searchTerm = '%' + searchTerm + '%';

        String query = 'SELECT Name, ExtId__c, Altura__C, Peso__c, TiposFiltrados__c, Imagen__c FROM Pokemon__c';

        if (searchTerm != '') {
        query += ' WHERE Name LIKE :searchTerm ';
        }
        if (tipo != 'Todos') {
        query += ' AND Tipos__c INCLUDES(:tipo) ';
        }
        if (generacion != 0) {
        query += ' AND Generacion__c =:generacion ';
        }
        if(orden == 'Tipo'){
            query += ' ORDER BY TiposFiltrados__c';

        }else if(orden == 'TiposDesc'){  
            query += ' ORDER BY TiposFiltrados__c DESC';
            
        }else if(orden == 'Nombre'){
            query += ' ORDER BY Name';

        }else if(orden == 'NombreDesc'){
            query += ' ORDER BY Name DESC';

        }else if(orden == 'Numero'){
            query += ' ORDER BY ExtId__c';
            
        }else{
            query += ' ORDER BY ExtId__c DESC';
        }
        

        return Database.query(query);
    }
}