force-app/main/default/objects/Pokemon__c/Pokemon__c.object-meta.xml
<CustomObject>
    <label>Pokemon</label>
    <nameField>
        <label>Pokemon Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pokemons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Pokemon__c/fields/Generacion__c.field-meta.xml
<CustomField>
    <fullName>Generacion__c</fullName>
    <formula>IF(ExtId__c  &gt;=1  &amp;&amp;  ExtId__c  &lt;=151, 1, (
 IF(ExtId__c  &gt;151  &amp;&amp;  ExtId__c  &lt;=251, 2, (
 IF(ExtId__c  &gt;251  &amp;&amp;  ExtId__c  &lt;=386, 3, (
 IF(ExtId__c  &gt;386  &amp;&amp;  ExtId__c  &lt;=493, 4, (
 IF(ExtId__c  &gt;493  &amp;&amp;  ExtId__c  &lt;=649, 5, (
 IF(ExtId__c  &gt;649  &amp;&amp;  ExtId__c  &lt;=721, 6, (
 IF(ExtId__c  &gt;721  &amp;&amp;  ExtId__c  &lt;=809, 7, (
 IF(ExtId__c  &gt;809  &amp;&amp;  ExtId__c  &lt;=898, 8, 0) )) )) )) )) )) )) ))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Generacion</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Pokemon__c/fields/Tipos__c.field-meta.xml
<CustomField>
    <fullName>Tipos__c</fullName>
    <label>Tipos</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Bug</fullName>
            </value>
            <value>
                <fullName>Dark</fullName>
            </value>
            <value>
                <fullName>Dragon</fullName>
            </value>
            <value>
                <fullName>Electric</fullName>
            </value>
            <value>
                <fullName>Fairy</fullName>
            </value>
            <value>
                <fullName>Fighting</fullName>
            </value>
            <value>
                <fullName>Fire</fullName>
            </value>
            <value>
                <fullName>Flying</fullName>
            </value>
            <value>
                <fullName>Ghost</fullName>
            </value>
            <value>
                <fullName>Grass</fullName>
            </value>
            <value>
                <fullName>Ground</fullName>
            </value>
            <value>
                <fullName>Ice</fullName>
            </value>
            <value>
                <fullName>Normal</fullName>
            </value>
            <value>
                <fullName>Poison</fullName>
            </value>
            <value>
                <fullName>Psychic</fullName>
            </value>
            <value>
                <fullName>Rock</fullName>
            </value>
            <value>
                <fullName>Steel</fullName>
            </value>
            <value>
                <fullName>Water</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PokemonControllerTest.cls
@isTest
private class PokemonControllerTest {
    
    @testSetup
    static void setup() {     
        
        Pokemon__c pokemon = new Pokemon__c(Name='Charmander', ExtId__c=4, Tipos__c='Fire');
        insert pokemon;      
    }
    
   @istest
    static void queryWithDefaultParameters(){
        
        Test.startTest();
        	List<Pokemon__c> pokemons = PokemonController.searchPokemons('Todos',0,'','');
        Test.stopTest();
        
        system.assertEquals(pokemons.size(),1);
        system.assertEquals(pokemons[0],[SELECT Id, Generacion__c, Name, ExtId__c, Tipos__c 
                                         FROM Pokemon__c 
                                         WHERE ExtId__c = 4]);
    }
    
    @istest
    static void queryWhithFullParameters(){
        
        Test.startTest();
        	List<Pokemon__c> pokemons = PokemonController.searchPokemons('Fire',1,'a','Numero');
        Test.stopTest();
        
        system.assertEquals(pokemons.size(),1);
        system.assertEquals(pokemons[0],[SELECT Id, Generacion__c, Name, ExtId__c, Tipos__c 
                                         FROM Pokemon__c 
                                         WHERE ExtId__c = 4]);

    }
    
    @istest
    static void queryWhithOrderByName(){
        
        Test.startTest();
        	List<Pokemon__c> pokemons = PokemonController.searchPokemons('Fire',1,'a','Nombre');
        Test.stopTest();
        
        system.assertEquals(pokemons.size(),1);
        system.assertEquals(pokemons[0],[SELECT Id, Generacion__c, Name, ExtId__c, Tipos__c 
                                         FROM Pokemon__c 
                                         WHERE ExtId__c = 4]);

    }
    
    @istest
    static void queryWhithOrderByNamesDesc(){
        
        Test.startTest();
        	List<Pokemon__c> pokemons = PokemonController.searchPokemons('Fire',1,'','NombreDesc');
        Test.stopTest();
        
        system.assertEquals(pokemons.size(),1);
        system.assertEquals(pokemons[0],[SELECT Id, Generacion__c, Name, ExtId__c, Tipos__c 
                                         FROM Pokemon__c 
                                         WHERE ExtId__c = 4]);
    }
    
    @istest
    static void queryWhithOrderByTypes(){
        
        Test.startTest();
        	List<Pokemon__c> pokemons = PokemonController.searchPokemons('Fire',1,'','Tipo');
        Test.stopTest();
        
        system.assertEquals(pokemons.size(),1);
        system.assertEquals(pokemons[0],[SELECT Id, Generacion__c, Name, ExtId__c, Tipos__c 
                                         FROM Pokemon__c 
                                         WHERE ExtId__c = 4]);
    }
    
    @istest
    static void queryWhithOrderByTypesDesc(){
        
        Test.startTest();
        	List<Pokemon__c> pokemons = PokemonController.searchPokemons('Fire',1,'','TiposDesc');
        Test.stopTest();
        
        system.assertEquals(pokemons.size(),1);
        system.assertEquals(pokemons[0],[SELECT Id, Generacion__c, Name, ExtId__c, Tipos__c 
                                         FROM Pokemon__c 
                                         WHERE ExtId__c = 4]);
    }   

}